In [1]:
import numpy as np

- Задание 1

Создайте матрицу 3 на 3, заполненную числами от 1 до 9

Прибавьте к ней матрицу с единицами на диагонале

Умножьте полученную матрицу на вектор (1, 2, 3)

Вычислить транспонированную матрицу A(T) от полученной в результате прибавления матрицы

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [2]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.eye(3)

In [3]:
m = matrix1 + matrix2
m

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [4]:
v = np.array([1, 2, 3])

In [5]:
res = m.dot(v)
res

array([15., 34., 53.])

In [6]:
np.transpose(m)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [7]:
np.linalg.inv(m)

array([[-6. , -2. ,  3. ],
       [-1. ,  0.5,  0. ],
       [ 5. ,  1. , -2. ]])

- Задание 2

Найдите собственные значения и собственные вектора матрицы:

In [8]:
m1 = np.array([[2, 2],
              [1, 3]])
m1

array([[2, 2],
       [1, 3]])

In [9]:
np.linalg.eig(m1)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

- Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!



In [10]:
m2 = np.array([[1, 2, 2], [1, 1, 1], [1, 2, 1]])
np.linalg.det(m2)

1.0