In [12]:
import numpy as np
import sympy as sym

Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:


[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию

Ярость

12 лет рабства

Однажды в Голливуде


In [2]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

- Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [9]:
np.dot(film_2, film_3) / (np.linalg.norm(film_2) * np.linalg.norm(film_3))
#косинус угла между векторами( скалярное произведение поделенное на перемноженные евклидовы нормы каждого из
#векторов)


0.40824829046386296

- Задание 2

Вычислить с помощью Python значение первой производной для функции

In [14]:
x = sym.Symbol('x')

In [15]:
3*x*(x**2+x)**3

3*x*(x**2 + x)**3

In [23]:
func = sym.diff(3*x*(x**2+x)**3, x)
func

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [20]:
func.subs(x, 1)

132

- Задание 3

Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [25]:
matrix1 = np.array([[0, 0, 0, 0, 1, 0], [0, 1, 0, 1, 0, 0], [0, 0, 1, 1, 1, 0], [1, 0, 0, 1, 0, 1]])
matrix1

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [27]:
matrix2 = np.array([1, 2, 3, 4])
matrix2

array([1, 2, 3, 4])

In [34]:
res = np.dot(matrix2, matrix1)
res

array([4, 2, 3, 9, 4, 4])